[package]
name = "rust-rapidsnark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< Updated upstream
thiserror = { workspace = true } 
=======
thiserror = { workspace = true }
>>>>>>> Stashed changes

[build]

[build-dependencies]
<<<<<<< Updated upstream
bindgen = { workspace = true } 
=======
bindgen = { workspace = true }
>>>>>>> Stashed changes
